-- ============================================================
-- SAVANNAH CINEMAS - PostgreSQL 18 MASTER SCHEMA
-- Converted from the Oracle schema
-- ============================================================

BEGIN;

-- ============================================================
-- CLEAN EXISTING OBJECTS
-- ============================================================
DROP TABLE IF EXISTS
    promotion_usage, booking_tickets, promotion_targets, promotions,
    ticket_prices, user_movie_views, user_cinema_favorites,
    user_favourites, user_notification_preferences, user_preferences,
    movie_reviews, customer_favourites, watchlist, tickets, payments,
    booking_seats, bookings, showtimes, movie_production_companies,
    production_companies, movie_images, movie_videos, movie_crew,
    movie_cast, movie_genres, movies, people, genres, studios, seats,
    screens, staff_profiles, customer_profiles, cinemas,
    user_role_assignments, user_roles, users
CASCADE;

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    forenames VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    phone_number VARCHAR(30),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT ck_users_active CHECK (is_active IN ('Y','N'))
);

COMMENT ON TABLE users IS 'Stores application user accounts';

-- ============================================================
-- CUSTOMER PROFILES
-- ============================================================
CREATE TABLE customer_profiles (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    date_of_birth DATE,
    gender VARCHAR(20),
    current_loyalty_points INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_customer_profile_user FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT ck_customer_loyalty CHECK (current_loyalty_points >= 0)
);
CREATE INDEX idx_customer_profiles_gender ON customer_profiles(gender);
CREATE INDEX idx_customer_profiles_loyalty_points ON customer_profiles(current_loyalty_points DESC);

-- ============================================================
-- USER ROLES
-- ============================================================
CREATE TABLE user_roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_user_roles_active CHECK (is_active IN ('Y','N'))
);
INSERT INTO user_roles(role_name,description) VALUES
('ADMIN','System Administrator with full access'),
('MANAGER','Manager with administrative privileges'),
('CUSTOMER','Regular customer with basic access'),
('STAFF','Cinema staff with operational access');

CREATE TABLE user_role_assignments (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_by BIGINT,
    CONSTRAINT pk_user_role_assignments PRIMARY KEY(user_id,role_id),
    CONSTRAINT fk_ura_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ura_role FOREIGN KEY(role_id) REFERENCES user_roles(role_id) ON DELETE CASCADE,
    CONSTRAINT fk_ura_assigned_by FOREIGN KEY(assigned_by) REFERENCES users(user_id) ON DELETE SET NULL
);

-- ============================================================
-- CINEMAS
-- ============================================================
CREATE TABLE cinemas (
    cinema_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    address VARCHAR(500),
    city VARCHAR(100),
    region VARCHAR(100),
    phone_number VARCHAR(30),
    email VARCHAR(150),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT ck_cinemas_active CHECK(is_active IN('Y','N'))
);

INSERT INTO cinemas(cinema_name,description,address,city,region,phone_number,email) VALUES
('Savannah Cinemas - Accra','Flagship Savannah Cinemas location','Accra','Accra','Greater Accra','+233 20 000 0000','accra@savannahcinemas.com');

-- ============================================================
-- SCREENS
-- ============================================================
CREATE TABLE screens (
    screen_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id BIGINT NOT NULL,
    screen_name VARCHAR(100) NOT NULL,
    screen_number INTEGER NOT NULL,
    capacity INTEGER NOT NULL,
    screen_type VARCHAR(50),
    sound_system VARCHAR(100),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_screens_cinema FOREIGN KEY(cinema_id) REFERENCES cinemas(cinema_id),
    CONSTRAINT uk_screen_number UNIQUE(cinema_id,screen_number),
    CONSTRAINT ck_screens_capacity CHECK(capacity > 0),
    CONSTRAINT ck_screens_active CHECK(is_active IN('Y','N'))
);

INSERT INTO screens(cinema_id,screen_name,screen_number,capacity,screen_type,sound_system) VALUES
(1,'Screen 1',1,10,'STANDARD','Dolby Digital'),
(1,'Screen 2',2,10,'VIP','Dolby Atmos');

-- ============================================================
-- SEATS
-- ============================================================
CREATE TABLE seats (
    seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT NOT NULL,
    row_label VARCHAR(10) NOT NULL,
    seat_number INTEGER NOT NULL,
    seat_label VARCHAR(20) NOT NULL,
    seat_type VARCHAR(30) DEFAULT 'STANDARD',
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_seats_screen FOREIGN KEY(screen_id) REFERENCES screens(screen_id),
    CONSTRAINT uk_seat_position UNIQUE(screen_id,row_label,seat_number),
    CONSTRAINT uk_seat_label UNIQUE(screen_id,seat_label),
    CONSTRAINT ck_seats_active CHECK(is_active IN('Y','N'))
);
CREATE INDEX idx_seats_screen_id ON seats(screen_id);
CREATE INDEX idx_seats_seat_type ON seats(seat_type);
CREATE INDEX idx_seats_active ON seats(is_active);

-- 5 rows x 10 seats for Screen 1; 2 wheelchair positions.
INSERT INTO seats(screen_id,row_label,seat_number,seat_label,seat_type)
SELECT 1, chr(64+r), s, chr(64+r)||s::text,
       CASE WHEN s IN(5,6) THEN 'VIP' ELSE 'STANDARD' END
FROM generate_series(1,5) AS r
CROSS JOIN generate_series(1,10) AS s;
INSERT INTO seats(screen_id,row_label,seat_number,seat_label,seat_type) VALUES
(1,'W',1,'W1','WHEELCHAIR'),(1,'W',2,'W2','WHEELCHAIR');

-- ============================================================
-- STAFF PROFILES
-- ============================================================
CREATE TABLE staff_profiles (
    staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    employee_number VARCHAR(50) NOT NULL UNIQUE,
    job_title VARCHAR(100),
    department VARCHAR(100),
    hire_date DATE,
    cinema_id BIGINT,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_staff_user FOREIGN KEY(user_id) REFERENCES users(user_id),
    CONSTRAINT fk_staff_cinema FOREIGN KEY(cinema_id) REFERENCES cinemas(cinema_id),
    CONSTRAINT ck_staff_active CHECK(is_active IN('Y','N'))
);

-- ============================================================
-- STUDIOS
-- ============================================================
CREATE TABLE studios (
    studio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studio_name VARCHAR(150) NOT NULL UNIQUE,
    country VARCHAR(100),
    website_url VARCHAR(500),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT ck_studios_active CHECK(is_active IN('Y','N'))
);

INSERT INTO studios(studio_name,country,website_url) VALUES
('Warner Bros. Pictures','USA','https://www.warnerbros.com'),
('Universal Pictures','USA','https://www.universalpictures.com'),
('Walt Disney Studios','USA','https://www.disney.com'),
('Sony Pictures','USA','https://www.sonypictures.com'),
('Paramount Pictures','USA','https://www.paramount.com'),
('20th Century Studios','USA','https://www.20thcenturystudios.com'),
('Lionsgate Films','USA','https://www.lionsgate.com'),
('A24 Films','USA','https://a24films.com'),
('Searchlight Pictures','USA','https://www.searchlightpictures.com'),
('StudioCanal','France','https://www.studiocanal.com');

-- ============================================================
-- GENRES
-- ============================================================
CREATE TABLE genres (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_genre_id INTEGER UNIQUE,
    genre_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
);
INSERT INTO genres(genre_name,description) VALUES
('Action','High-energy films with physical feats, fights, and stunts'),
('Adventure','Exciting journeys, exploration, and quests'),
('Animation','Films created through animation techniques'),
('Biography','Dramatized accounts of real people''s lives'),
('Comedy','Humorous films designed to entertain and amuse'),
('Crime','Films centered around criminal activities and investigations'),
('Documentary','Factual films documenting real events and people'),
('Drama','Serious, emotional narratives focusing on character development'),
('Family','Films suitable for viewers of all ages'),
('Fantasy','Films featuring magic, mythical creatures, and imaginary worlds'),
('History','Films dramatizing historical events and periods'),
('Horror','Films designed to frighten and evoke fear'),
('Music','Films centered around music, musicians, or musical performances'),
('Musical','Films featuring characters singing and dancing'),
('Mystery','Films centered around solving puzzles or crimes'),
('Romance','Films focusing on romantic relationships and love stories'),
('Sci-Fi','Science fiction films exploring futuristic concepts and technology'),
('Sport','Films centered around sports and athletic competition'),
('Thriller','Suspenseful films designed to create tension and excitement'),
('War','Films depicting warfare and military conflicts'),
('Western','Films set in the American Old West'),
('Black Comedy','Humorous films dealing with dark and serious subjects'),
('Cyberpunk','Sci-Fi subgenre focusing on high-tech and low-life'),
('Dark Fantasy','Fantasy with horror or gothic elements'),
('Mockumentary','Fictional films presented as documentaries'),
('Neo-Noir','Modern films with film-noir elements'),
('Romantic Comedy','Combination of romance and comedy'),
('Space Opera','Sci-Fi with epic adventures in space'),
('Superhero','Films featuring superhero characters'),
('Teen Drama','Dramas focused on teenage characters and issues');

-- ============================================================
-- PEOPLE
-- ============================================================
CREATE TABLE people (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_person_id INTEGER UNIQUE,
    name VARCHAR(200) NOT NULL,
    original_name VARCHAR(200),
    profile_url VARCHAR(500),
    gender INTEGER,
    known_for_department VARCHAR(100),
    popularity NUMERIC(10,3),
    biography TEXT,
    birth_date DATE,
    death_date DATE,
    place_of_birth VARCHAR(300),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
);

-- ============================================================
-- MOVIES
-- ============================================================
CREATE TABLE movies (
    movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER UNIQUE,
    title VARCHAR(200) NOT NULL,
    original_title VARCHAR(200),
    description TEXT,
    release_date DATE,
    runtime_minutes INTEGER,
    age_rating VARCHAR(20),
    poster_url VARCHAR(500),
    backdrop_url VARCHAR(500),
    trailer_url VARCHAR(500),
    rating NUMERIC(3,1),
    status VARCHAR(30) DEFAULT 'UPCOMING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    studio_id BIGINT,
    CONSTRAINT fk_movies_studio FOREIGN KEY(studio_id) REFERENCES studios(studio_id),
    CONSTRAINT ck_movies_rating CHECK(rating IS NULL OR(rating >= 0 AND rating <= 10)),
    CONSTRAINT ck_movies_status CHECK(status IN('UPCOMING','NOW_SHOWING','ENDED','ARCHIVED'))
);
CREATE INDEX idx_movies_tmdb_id ON movies(tmdb_id);
CREATE INDEX idx_movies_status ON movies(status);
CREATE INDEX idx_movies_release_date ON movies(release_date);

-- ============================================================
-- MOVIE GENRES / CAST / CREW / VIDEOS / IMAGES
-- ============================================================
CREATE TABLE movie_genres (
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY(movie_id,genre_id),
    FOREIGN KEY(movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE,
    FOREIGN KEY(genre_id) REFERENCES genres(genre_id)
);
CREATE INDEX idx_movie_genres_genre ON movie_genres(genre_id);

CREATE TABLE movie_cast (
    movie_cast_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    person_id BIGINT NOT NULL REFERENCES people(person_id),
    character_name VARCHAR(300),
    cast_order INTEGER,
    credit_id VARCHAR(100),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_movie_cast UNIQUE(movie_id,person_id,character_name)
);
CREATE INDEX idx_movie_cast_movie ON movie_cast(movie_id);
CREATE INDEX idx_movie_cast_person ON movie_cast(person_id);

CREATE TABLE movie_crew (
    movie_crew_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    person_id BIGINT NOT NULL REFERENCES people(person_id),
    department VARCHAR(100),
    job VARCHAR(200),
    credit_id VARCHAR(100),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_movie_crew UNIQUE(movie_id,person_id,job)
);
CREATE INDEX idx_movie_crew_movie ON movie_crew(movie_id);
CREATE INDEX idx_movie_crew_person ON movie_crew(person_id);

CREATE TABLE movie_videos (
    video_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    tmdb_video_id VARCHAR(100) UNIQUE,
    video_name VARCHAR(300) NOT NULL,
    video_key VARCHAR(200) NOT NULL,
    site VARCHAR(50),
    video_type VARCHAR(50),
    official CHAR(1) DEFAULT 'N' NOT NULL,
    published_at TIMESTAMP(6),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_movie_videos_official CHECK(official IN('Y','N'))
);
CREATE INDEX idx_movie_videos_movie ON movie_videos(movie_id);

CREATE TABLE movie_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    image_type VARCHAR(30) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    image_url VARCHAR(700),
    width INTEGER,
    height INTEGER,
    aspect_ratio NUMERIC(10,4),
    language VARCHAR(20),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_movie_images_type CHECK(image_type IN('POSTER','BACKDROP','LOGO'))
);
CREATE INDEX idx_movie_images_movie ON movie_images(movie_id);

-- ============================================================
-- PRODUCTION COMPANIES
-- ============================================================
CREATE TABLE production_companies (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_company_id INTEGER UNIQUE,
    company_name VARCHAR(300) NOT NULL,
    logo_url VARCHAR(500),
    country_code VARCHAR(10),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE TABLE movie_production_companies (
    movie_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(movie_id,company_id),
    FOREIGN KEY(movie_id) REFERENCES movies(movie_id),
    FOREIGN KEY(company_id) REFERENCES production_companies(company_id)
);
CREATE INDEX idx_movie_prod_comp_company ON movie_production_companies(company_id);

-- ============================================================
-- SHOWTIMES
-- ============================================================
CREATE TABLE showtimes (
    showtime_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    cinema_id BIGINT NOT NULL REFERENCES cinemas(cinema_id),
    screen_id BIGINT NOT NULL REFERENCES screens(screen_id),
    show_date DATE NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    ticket_price NUMERIC(10,2) NOT NULL,
    status VARCHAR(30) DEFAULT 'SCHEDULED' NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT ck_showtimes_price CHECK(ticket_price >= 0),
    CONSTRAINT ck_showtimes_status CHECK(status IN('SCHEDULED','NOW_SHOWING','COMPLETED','CANCELLED')),
    CONSTRAINT ck_showtimes_active CHECK(is_active IN('Y','N')),
    CONSTRAINT fk_showtimes_screen_cinema FOREIGN KEY(screen_id,cinema_id)
        REFERENCES screens(screen_id,cinema_id) DEFERRABLE INITIALLY IMMEDIATE
);

-- Composite uniqueness needed by the FK above.
ALTER TABLE screens ADD CONSTRAINT uk_screens_id_cinema UNIQUE(screen_id,cinema_id);

CREATE INDEX idx_showtimes_movie_id ON showtimes(movie_id);
CREATE INDEX idx_showtimes_cinema_id ON showtimes(cinema_id);
CREATE INDEX idx_showtimes_screen_id ON showtimes(screen_id);
CREATE INDEX idx_showtimes_show_date ON showtimes(show_date);
CREATE INDEX idx_showtimes_start_time ON showtimes(start_time);
CREATE INDEX idx_showtimes_status ON showtimes(status);
CREATE INDEX idx_showtimes_active ON showtimes(is_active);
CREATE INDEX idx_showtimes_date_status ON showtimes(show_date,status);
CREATE INDEX idx_showtimes_cinema_date ON showtimes(cinema_id,show_date);

-- ============================================================
-- TICKET PRICES
-- ============================================================
CREATE TABLE ticket_prices (
    price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id BIGINT NOT NULL REFERENCES cinemas(cinema_id),
    screen_id BIGINT REFERENCES screens(screen_id),
    price_name VARCHAR(100) NOT NULL,
    ticket_type VARCHAR(30) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'GHS' NOT NULL,
    day_type VARCHAR(20),
    start_time TIMESTAMP(6),
    end_time TIMESTAMP(6),
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_ticket_prices_amount CHECK(amount >= 0),
    CONSTRAINT ck_ticket_prices_active CHECK(is_active IN('Y','N'))
);
INSERT INTO ticket_prices(cinema_id,screen_id,price_name,ticket_type,amount,currency,day_type) VALUES
(1,NULL,'Adult Weekday','ADULT',60,'GHS','WEEKDAY'),
(1,NULL,'Child Weekday','CHILD',40,'GHS','WEEKDAY'),
(1,NULL,'Student Weekday','STUDENT',45,'GHS','WEEKDAY'),
(1,NULL,'Adult Weekend','ADULT',70,'GHS','WEEKEND'),
(1,NULL,'Child Weekend','CHILD',50,'GHS','WEEKEND'),
(1,NULL,'Student Weekend','STUDENT',55,'GHS','WEEKEND'),
(1,NULL,'VIP','VIP',100,'GHS',NULL);

-- ============================================================
-- PROMOTIONS
-- ============================================================
CREATE TABLE promotions (
    promotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id BIGINT REFERENCES cinemas(cinema_id),
    promotion_name VARCHAR(150) NOT NULL,
    promotion_code VARCHAR(50) UNIQUE,
    description VARCHAR(1000),
    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(10,2) NOT NULL,
    min_tickets INTEGER,
    max_discount NUMERIC(10,2),
    start_date TIMESTAMP(6) NOT NULL,
    end_date TIMESTAMP(6) NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_promotions_discount_type CHECK(discount_type IN('PERCENTAGE','FIXED')),
    CONSTRAINT ck_promotions_discount_value CHECK(discount_value >= 0),
    CONSTRAINT ck_promotions_min_tickets CHECK(min_tickets IS NULL OR min_tickets > 0),
    CONSTRAINT ck_promotions_max_discount CHECK(max_discount IS NULL OR max_discount >= 0),
    CONSTRAINT ck_promotions_status CHECK(is_active IN('Y','N')),
    CONSTRAINT ck_promotions_dates CHECK(end_date >= start_date)
);
INSERT INTO promotions(cinema_id,promotion_name,promotion_code,description,discount_type,discount_value,min_tickets,max_discount,start_date,end_date) VALUES
(1,'Opening Special','WELCOME20','20% off movie tickets during the Savannah Cinemas opening period.','PERCENTAGE',20,NULL,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + INTERVAL '30 days'),
(1,'Group Movie Night',NULL,'Get 15% off when purchasing four or more tickets.','PERCENTAGE',15,4,60,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + INTERVAL '90 days'),
(1,'Student Movie Night','STUDENT15','Students receive 15% off eligible bookings.','PERCENTAGE',15,NULL,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + INTERVAL '90 days'),
(1,'Early Bird','EARLYBIRD','GHS 10 off selected bookings.','FIXED',10,NULL,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + INTERVAL '60 days');

CREATE TABLE promotion_targets (
    target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL REFERENCES promotions(promotion_id),
    target_type VARCHAR(30) NOT NULL,
    target_value VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_promotion_target_type CHECK(target_type IN('MOVIE','TICKET_TYPE','SCREEN','CINEMA'))
);
INSERT INTO promotion_targets(promotion_id,target_type,target_value)
SELECT promotion_id,'TICKET_TYPE','STUDENT' FROM promotions WHERE promotion_code='STUDENT15';

-- ============================================================
-- BOOKINGS
-- ============================================================
CREATE TABLE bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref VARCHAR(30) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    showtime_id BIGINT NOT NULL REFERENCES showtimes(showtime_id),
    ticket_quantity INTEGER DEFAULT 1 NOT NULL,
    ticket_price NUMERIC(10,2) NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(30) DEFAULT 'CONFIRMED' NOT NULL,
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    promotion_id BIGINT REFERENCES promotions(promotion_id),
    discount_amount NUMERIC(10,2) DEFAULT 0 NOT NULL,
    CONSTRAINT ck_bookings_quantity CHECK(ticket_quantity > 0),
    CONSTRAINT ck_bookings_price CHECK(ticket_price >= 0),
    CONSTRAINT ck_bookings_total CHECK(total_amount >= 0),
    CONSTRAINT ck_bookings_status CHECK(status IN('PENDING','CONFIRMED','CANCELLED','COMPLETED')),
    CONSTRAINT ck_bookings_discount CHECK(discount_amount >= 0)
);
CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_showtime ON bookings(showtime_id);
CREATE INDEX idx_bookings_status ON bookings(status);

CREATE TABLE booking_tickets (
    booking_ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(booking_id),
    ticket_type VARCHAR(30) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_booking_tickets_quantity CHECK(quantity > 0),
    CONSTRAINT ck_booking_tickets_unit_price CHECK(unit_price >= 0),
    CONSTRAINT ck_booking_tickets_subtotal CHECK(subtotal >= 0)
);
CREATE INDEX idx_booking_tickets_booking ON booking_tickets(booking_id);

CREATE TABLE booking_seats (
    booking_seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE,
    showtime_id BIGINT NOT NULL REFERENCES showtimes(showtime_id),
    seat_id BIGINT NOT NULL REFERENCES seats(seat_id),
    ticket_price NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_booking_showtime_seat UNIQUE(showtime_id,seat_id),
    CONSTRAINT ck_booking_seats_price CHECK(ticket_price >= 0)
);
CREATE INDEX idx_booking_seats_booking ON booking_seats(booking_id);
CREATE INDEX idx_booking_seats_showtime ON booking_seats(showtime_id);
CREATE INDEX idx_booking_seats_seat ON booking_seats(seat_id);

-- ============================================================
-- PAYMENTS
-- ============================================================
CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(booking_id),
    payment_reference VARCHAR(100) NOT NULL UNIQUE,
    amount NUMERIC(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'GHS' NOT NULL,
    payment_method VARCHAR(30),
    status VARCHAR(30) NOT NULL,
    transaction_reference VARCHAR(150),
    payment_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT ck_payments_amount CHECK(amount >= 0)
);
CREATE INDEX idx_payments_booking ON payments(booking_id);
CREATE INDEX idx_payments_status ON payments(status);

-- ============================================================
-- TICKETS
-- ============================================================
CREATE TABLE tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(booking_id),
    ticket_code VARCHAR(100) NOT NULL UNIQUE,
    qr_code_data VARCHAR(500) NOT NULL,
    status VARCHAR(30) DEFAULT 'VALID' NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT ck_tickets_status CHECK(status IN('VALID','USED','CANCELLED','EXPIRED'))
);
CREATE INDEX idx_tickets_status ON tickets(status);
CREATE INDEX idx_tickets_used_at ON tickets(used_at);
CREATE INDEX idx_tickets_created ON tickets(created_at);

-- ============================================================
-- USER FEATURES
-- ============================================================
CREATE TABLE watchlist (
    watchlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    film_id BIGINT NOT NULL REFERENCES movies(movie_id),
    title VARCHAR(255) NOT NULL,
    year INTEGER,
    poster_url VARCHAR(1000),
    rating NUMERIC(3,1),
    watched CHAR(1) DEFAULT 'N' NOT NULL,
    favorite CHAR(1) DEFAULT 'N' NOT NULL,
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    watched_date TIMESTAMP,
    CONSTRAINT uq_watchlist_user_film UNIQUE(user_id,film_id),
    CONSTRAINT ck_watchlist_watched CHECK(watched IN('Y','N')),
    CONSTRAINT ck_watchlist_favorite CHECK(favorite IN('Y','N'))
);

CREATE TABLE user_favourites (
    favourite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    favourite_type VARCHAR(30) NOT NULL,
    reference_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_user_favourites_type CHECK(favourite_type IN('MOVIE','CINEMA')),
    CONSTRAINT uk_user_favourite UNIQUE(user_id,favourite_type,reference_id)
);

CREATE TABLE user_cinema_favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    cinema_id BIGINT NOT NULL REFERENCES cinemas(cinema_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_cinema_favorite UNIQUE(user_id,cinema_id)
);

CREATE TABLE user_movie_views (
    view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    view_count INTEGER DEFAULT 1 NOT NULL,
    first_viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_movie_view UNIQUE(user_id,movie_id),
    CONSTRAINT ck_user_movie_view_count CHECK(view_count > 0)
);

CREATE TABLE movie_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
    rating NUMERIC(2,1) NOT NULL,
    review_text VARCHAR(2000),
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_movie_reviews_rating CHECK(rating >= 1 AND rating <= 5),
    CONSTRAINT ck_movie_reviews_status CHECK(status IN('PUBLISHED','HIDDEN','DELETED')),
    CONSTRAINT uk_user_movie_review UNIQUE(user_id,movie_id)
);

CREATE TABLE user_preferences (
    preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    preference_type VARCHAR(30) NOT NULL,
    preference_value VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_user_preferences_type CHECK(preference_type IN('GENRE','LANGUAGE','AGE_RATING','CINEMA')),
    CONSTRAINT uk_user_preference UNIQUE(user_id,preference_type,preference_value)
);

CREATE TABLE user_notification_preferences (
    notification_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(user_id),
    booking_reminders CHAR(1) DEFAULT 'Y' NOT NULL,
    booking_confirmations CHAR(1) DEFAULT 'Y' NOT NULL,
    movie_releases CHAR(1) DEFAULT 'Y' NOT NULL,
    promotions CHAR(1) DEFAULT 'Y' NOT NULL,
    new_movies CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_booking_reminders CHECK(booking_reminders IN('Y','N')),
    CONSTRAINT ck_booking_confirmations CHECK(booking_confirmations IN('Y','N')),
    CONSTRAINT ck_movie_releases CHECK(movie_releases IN('Y','N')),
    CONSTRAINT ck_promotions CHECK(promotions IN('Y','N')),
    CONSTRAINT ck_new_movies CHECK(new_movies IN('Y','N'))
);

-- ============================================================
-- PROMOTION USAGE
-- ============================================================
CREATE TABLE promotion_usage (
    promotion_usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL REFERENCES promotions(promotion_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(booking_id),
    discount_amount NUMERIC(10,2) NOT NULL,
    used_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_promo_usage_amount CHECK(discount_amount >= 0)
);

-- ============================================================
-- UPDATED_AT FUNCTION / TRIGGER
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'customer_profiles','staff_profiles','cinemas','screens','studios','genres',
        'people','movies','production_companies','showtimes','ticket_prices',
        'promotions','bookings','payments','tickets','movie_reviews',
        'user_preferences','user_notification_preferences'
    ] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I',t,t);
        EXECUTE format('CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',t,t);
    END LOOP;
END $$;

-- ============================================================
-- MOVIE STATUS FUNCTION
-- ============================================================
CREATE OR REPLACE FUNCTION calculate_movie_status(p_release_date DATE)
RETURNS VARCHAR(30)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_release_date IS NULL THEN
        RETURN 'UPCOMING';
    ELSIF p_release_date > CURRENT_DATE THEN
        RETURN 'UPCOMING';
    ELSIF EXTRACT(YEAR FROM p_release_date) = EXTRACT(YEAR FROM CURRENT_DATE) THEN
        RETURN 'NOW_SHOWING';
    ELSIF p_release_date < CURRENT_DATE THEN
        RETURN 'ENDED';
    END IF;
    RETURN 'UPCOMING';
END;
$$;

CREATE OR REPLACE FUNCTION trg_movies_status()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.status := calculate_movie_status(NEW.release_date);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_movies_status
BEFORE INSERT OR UPDATE OF release_date ON movies
FOR EACH ROW EXECUTE FUNCTION trg_movies_status();

-- ============================================================
-- SHOWTIME END TIME
-- ============================================================
CREATE OR REPLACE FUNCTION calculate_showtime_end()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_runtime INTEGER;
BEGIN
    SELECT runtime_minutes INTO v_runtime
    FROM movies
    WHERE movie_id = NEW.movie_id;

    IF v_runtime IS NOT NULL AND NEW.start_time IS NOT NULL THEN
        NEW.end_time := NEW.start_time + make_interval(mins => v_runtime);
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_showtimes_end_time
BEFORE INSERT OR UPDATE OF start_time,movie_id ON showtimes
FOR EACH ROW EXECUTE FUNCTION calculate_showtime_end();

-- ============================================================
-- BOOKING TOTAL
-- ============================================================
CREATE OR REPLACE FUNCTION calculate_booking_total()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.total_amount := GREATEST((NEW.ticket_quantity * NEW.ticket_price) - COALESCE(NEW.discount_amount,0),0);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_bookings_total
BEFORE INSERT OR UPDATE OF ticket_quantity,ticket_price,discount_amount ON bookings
FOR EACH ROW EXECUTE FUNCTION calculate_booking_total();

-- ============================================================
-- PAYMENT / TICKET TIMESTAMPS
-- ============================================================
CREATE OR REPLACE FUNCTION update_payment_date()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status = 'COMPLETED' AND COALESCE(OLD.status,'') <> 'COMPLETED' THEN
        NEW.payment_date := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_payments_completed
BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION update_payment_date();

CREATE OR REPLACE FUNCTION update_ticket_used_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status = 'USED' AND COALESCE(OLD.status,'') <> 'USED' THEN
        NEW.used_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_tickets_used
BEFORE UPDATE ON tickets
FOR EACH ROW EXECUTE FUNCTION update_ticket_used_at();

COMMIT;

-- ============================================================
-- VERIFY
-- ============================================================
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
