-- ============================================================
-- DROP DIMENSIONS (Reverse Order - Children First)
-- ============================================================

-- Drop tables with foreign key references first
DROP TABLE dim_customer CASCADE CONSTRAINTS;
DROP TABLE dim_movie CASCADE CONSTRAINTS;
DROP TABLE dim_screen CASCADE CONSTRAINTS;
DROP TABLE dim_seat CASCADE CONSTRAINTS;
DROP TABLE dim_branch CASCADE CONSTRAINTS;
DROP TABLE dim_employee CASCADE CONSTRAINTS;
DROP TABLE dim_product CASCADE CONSTRAINTS;
DROP TABLE dim_promotion CASCADE CONSTRAINTS;
DROP TABLE dim_supplier CASCADE CONSTRAINTS;

-- Drop reference tables
DROP TABLE dim_channel CASCADE CONSTRAINTS;
DROP TABLE dim_showtime CASCADE CONSTRAINTS;
DROP TABLE dim_certification CASCADE CONSTRAINTS;
DROP TABLE dim_membership_tier CASCADE CONSTRAINTS;
DROP TABLE dim_age_group CASCADE CONSTRAINTS;
DROP TABLE dim_geography CASCADE CONSTRAINTS;
DROP TABLE dim_device CASCADE CONSTRAINTS;
DROP TABLE dim_movie_status CASCADE CONSTRAINTS;
DROP TABLE dim_genre CASCADE CONSTRAINTS;
DROP TABLE dim_payment CASCADE CONSTRAINTS;
DROP TABLE dim_time CASCADE CONSTRAINTS;
DROP TABLE dim_date CASCADE CONSTRAINTS;


-- =====================================================
-- DIMENSION TABLES 
-- =====================================================

-- ============================================================
-- HOLIDAYS - Static Ghana public holidays (recurring annually)
-- ============================================================
CREATE TABLE HOLIDAYS (
    HOLIDAY_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY 
                        INCREMENT BY 1 START WITH 1 PRIMARY KEY,
    HOLIDAY_DATE        VARCHAR2(5) NOT NULL CHECK (REGEXP_LIKE(HOLIDAY_DATE, '^\d{2}-\d{2}$')),
    HOLIDAY_NAME        VARCHAR2(50) NOT NULL,
    CONSTRAINT UQ_HOLIDAY_DATE UNIQUE (HOLIDAY_DATE)
);

COMMENT ON TABLE HOLIDAYS IS 'Static Ghana public holidays (recurring annually).';
COMMENT ON COLUMN HOLIDAYS.HOLIDAY_DATE IS 'Format: DD-MM (e.g., 06-03 for Independence Day)';
COMMENT ON COLUMN HOLIDAYS.HOLIDAY_NAME IS 'Name of the holiday';

-- ============================================================
-- SEED DATA: Ghana Public Holidays
-- ============================================================
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('01-01', 'New Year''s Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('01-05', 'Labour Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('06-03', 'Independence Day'),
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('07-04', 'Republic Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('01-08', 'National Farmers Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('04-08', 'Founders Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('21-09', 'Kwame Nkrumah Memorial Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('25-12', 'Christmas Day');
INSERT INTO HOLIDAYS (holiday_date, holiday_name) VALUES ('26-12', 'Boxing Day');

COMMIT;


-- ============================================================
-- DIM_DATE - Date dimension for all dates within given range
-- ============================================================
CREATE TABLE DIM_DATE (
    DATE_ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY 
                            INCREMENT BY 1 START WITH 1 PRIMARY KEY,
    YEAR                    VARCHAR2(5 BYTE),
    MONTH                   VARCHAR2(5 BYTE),
    DAY                     VARCHAR2(5 BYTE),
    FULL_DATE               DATE,
    MONTH_NAME              VARCHAR2(10 BYTE),
    QTR                     VARCHAR2(1 BYTE),
    DAY_OF_WEEK             VARCHAR2(10 BYTE),
    DAY_IN_WEEK             VARCHAR2(1 BYTE),
    DAY_IN_YEAR             VARCHAR2(5 BYTE),
    WEEK_IN_MONTH           VARCHAR2(1 BYTE),
    WEEK_IN_YEAR            VARCHAR2(2 BYTE),
    IS_LEAP_YEAR            NUMBER(1) DEFAULT 0 NOT NULL,    
    IS_HOLIDAY              NUMBER(1) DEFAULT 0 NOT NULL,   
    HOLIDAY_ID              NUMBER,
    CONSTRAINT FK_DIM_DATE_HOLIDAY FOREIGN KEY (HOLIDAY_ID) 
        REFERENCES HOLIDAYS (HOLIDAY_ID)
);

COMMENT ON TABLE DIM_DATE IS 'Calendar dimension';
COMMENT ON COLUMN DIM_DATE.FULL_DATE IS 'Oracle DATE value';
COMMENT ON COLUMN DIM_DATE.HOLIDAY_ID IS 'Foreign key to HOLIDAYS';


-- ============================================================
-- DIM_TIME - Time of day dimension
-- ============================================================
CREATE TABLE dim_time (
    time_id			NUMBER GENERATED BY DEFAULT AS IDENTITY INCREMENT BY 1 START WITH 1 PRIMARY KEY,
	full_time		VARCHAR2(10) NOT NULL,
	hour_24			NUMBER(2) NOT NULL,
	minute_number	NUMBER(2) NOT NULL,
	second_number	NUMBER(2) NOT NULL
);

COMMENT ON TABLE DIM_TIME IS 'Time of day dimension';



-- ============================================================
-- DIM_GENRE - Movie genre dimension
-- ============================================================
CREATE TABLE dim_genre (
    genre_sk            NUMBER(12)      CONSTRAINT pk_dim_genre PRIMARY KEY,
    genre_id            VARCHAR2(20)    NOT NULL,
    genre_code          VARCHAR2(20)    NOT NULL,
    genre_name          VARCHAR2(50)    NOT NULL,
    genre_description   VARCHAR2(255),
    tmdb_genre_id       NUMBER(6),
    genre_category      VARCHAR2(30),
    genre_parent_sk     NUMBER(12),
    display_order       NUMBER(3),
    color_code          VARCHAR2(7),
    icon_class          VARCHAR2(50),
    is_active           CHAR(1)         DEFAULT 'Y',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_genre_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_dim_genre_category CHECK (genre_category IN ('ACTION', 'DRAMA', 'COMEDY', 'HORROR', 'SCI_FI', 'FANTASY', 'DOCUMENTARY', 'ANIMATION', 'ROMANCE', 'THRILLER', 'OTHER'))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_genre_id ON dim_genre(genre_id);
CREATE UNIQUE INDEX uk_dim_genre_code ON dim_genre(genre_code);

-- Foreign key
ALTER TABLE dim_genre ADD CONSTRAINT fk_dim_genre_parent 
    FOREIGN KEY (genre_parent_sk) REFERENCES dim_genre(genre_sk);

-- Indexes
CREATE INDEX idx_dim_genre_name ON dim_genre(genre_name);
CREATE INDEX idx_dim_genre_category ON dim_genre(genre_category);

COMMENT ON TABLE dim_genre IS 'Movie genre reference dimension';


-- ============================================================
-- DIM_CHANNEL - Booking and sales channel dimension
-- ============================================================
CREATE TABLE dim_channel (
    channel_sk          NUMBER(12)      CONSTRAINT pk_dim_channel PRIMARY KEY,
    channel_id          VARCHAR2(20)    NOT NULL,
    channel_code        VARCHAR2(20)    NOT NULL,
    channel_name        VARCHAR2(50)    NOT NULL,
    channel_description VARCHAR2(255),
    channel_type        VARCHAR2(30)    NOT NULL,
    channel_category    VARCHAR2(30)    NOT NULL,
    is_self_service     CHAR(1)         DEFAULT 'N',
    requires_human      CHAR(1)         DEFAULT 'Y',
    is_remote           CHAR(1)         DEFAULT 'N',
    booking_fee_rate    NUMBER(5,2)     DEFAULT 0,
    booking_fee_fixed   NUMBER(5,2)     DEFAULT 0,
    commission_rate     NUMBER(5,2)     DEFAULT 0,
    is_active           CHAR(1)         DEFAULT 'Y',
    display_order       NUMBER(3),
    icon_class          VARCHAR2(50),
    color_code          VARCHAR2(7),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_channel_self CHECK (is_self_service IN ('Y','N')),
    CONSTRAINT chk_dim_channel_human CHECK (requires_human IN ('Y','N')),
    CONSTRAINT chk_dim_channel_remote CHECK (is_remote IN ('Y','N')),
    CONSTRAINT chk_dim_channel_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_dim_channel_type CHECK (channel_type IN ('ONLINE', 'MOBILE_APP', 'BOX_OFFICE', 'KIOSK', 'POS_TERMINAL', 'THIRD_PARTY', 'CALL_CENTER', 'OTHER')),
    CONSTRAINT chk_dim_channel_category CHECK (channel_category IN ('DIGITAL', 'PHYSICAL', 'THIRD_PARTY'))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_channel_id ON dim_channel(channel_id);
CREATE UNIQUE INDEX uk_dim_channel_code ON dim_channel(channel_code);

-- Indexes
CREATE INDEX idx_dim_channel_type ON dim_channel(channel_type);

COMMENT ON TABLE dim_channel IS 'Booking and sales channel dimension';


-- ============================================================
-- DIM_PAYMENT - Payment method dimension
-- ============================================================
CREATE TABLE dim_payment (
    payment_sk          NUMBER(12)      CONSTRAINT pk_dim_payment PRIMARY KEY,
    payment_id          VARCHAR2(20)    NOT NULL,
    payment_code        VARCHAR2(20)    NOT NULL,
    payment_name        VARCHAR2(50)    NOT NULL,
    payment_description VARCHAR2(255),
    payment_category    VARCHAR2(30)    NOT NULL,
    payment_subcategory VARCHAR2(30),
    is_digital          CHAR(1)         DEFAULT 'N',
    is_prepaid          CHAR(1)         DEFAULT 'N',
    requires_pin        CHAR(1)         DEFAULT 'N',
    requires_cvv        CHAR(1)         DEFAULT 'N',
    requires_otp        CHAR(1)         DEFAULT 'N',
    processing_fee_rate NUMBER(5,2)     DEFAULT 0,
    processing_fee_fixed NUMBER(5,2)    DEFAULT 0,
    settlement_days     NUMBER(3)       DEFAULT 1,
    is_active           CHAR(1)         DEFAULT 'Y',
    display_order       NUMBER(3),
    icon_class          VARCHAR2(50),
    color_code          VARCHAR2(7),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_payment_digital CHECK (is_digital IN ('Y','N')),
    CONSTRAINT chk_dim_payment_prepaid CHECK (is_prepaid IN ('Y','N')),
    CONSTRAINT chk_dim_payment_pin CHECK (requires_pin IN ('Y','N')),
    CONSTRAINT chk_dim_payment_cvv CHECK (requires_cvv IN ('Y','N')),
    CONSTRAINT chk_dim_payment_otp CHECK (requires_otp IN ('Y','N')),
    CONSTRAINT chk_dim_payment_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_dim_payment_category CHECK (payment_category IN ('CASH', 'CARD', 'MOBILE_MONEY', 'GIFT_CARD', 'VOUCHER', 'BANK_TRANSFER', 'CRYPTO', 'LOYALTY_POINTS', 'OTHER'))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_payment_id ON dim_payment(payment_id);
CREATE UNIQUE INDEX uk_dim_payment_code ON dim_payment(payment_code);

-- Indexes
CREATE INDEX idx_dim_payment_category ON dim_payment(payment_category);

COMMENT ON TABLE dim_payment IS 'Payment method dimension';


-- ============================================================
-- DIM_CERTIFICATION - Content rating dimension
-- ============================================================
CREATE TABLE dim_certification (
    cert_sk             NUMBER(12)      CONSTRAINT pk_dim_cert PRIMARY KEY,
    cert_id             VARCHAR2(20)    NOT NULL,
    cert_code           VARCHAR2(20)    NOT NULL,
    cert_name           VARCHAR2(50)    NOT NULL,
    cert_description    VARCHAR2(255),
    min_age             NUMBER(3),
    max_age             NUMBER(3),
    age_group           VARCHAR2(20),
    certification_board VARCHAR2(50)    DEFAULT 'GHANA',
    country             VARCHAR2(50)    DEFAULT 'Ghana',
    is_adult_content    CHAR(1)         DEFAULT 'N',
    requires_guardian   CHAR(1)         DEFAULT 'N',
    display_order       NUMBER(3),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_cert_adult CHECK (is_adult_content IN ('Y','N')),
    CONSTRAINT chk_dim_cert_guardian CHECK (requires_guardian IN ('Y','N')),
    CONSTRAINT chk_dim_cert_age_group CHECK (age_group IN ('ALL', 'CHILDREN', 'TEEN', 'YOUNG_ADULT', 'ADULT', 'MATURE')),
    CONSTRAINT chk_dim_cert_min_age CHECK (min_age >= 0),
    CONSTRAINT chk_dim_cert_max_age CHECK (max_age IS NULL OR max_age >= min_age)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_cert_id ON dim_certification(cert_id);
CREATE UNIQUE INDEX uk_dim_cert_code ON dim_certification(cert_code);

-- Indexes
CREATE INDEX idx_dim_cert_min_age ON dim_certification(min_age);

COMMENT ON TABLE dim_certification IS 'Content rating dimension (PG, PG-13, R, etc.)';


-- ============================================================
-- DIM_MEMBERSHIP_TIER - Loyalty program tier dimension
-- ============================================================
CREATE TABLE dim_membership_tier (
    tier_sk             NUMBER(12)      CONSTRAINT pk_dim_tier PRIMARY KEY,
    tier_id             VARCHAR2(20)    NOT NULL,
    tier_code           VARCHAR2(20)    NOT NULL,
    tier_name           VARCHAR2(30)    NOT NULL,
    tier_description    VARCHAR2(255),
    points_required     NUMBER(10)      NOT NULL,
    annual_spend_required NUMBER(12,2)  NOT NULL,
    visit_required      NUMBER(6)       NOT NULL,
    discount_percentage NUMBER(5,2)     DEFAULT 0,
    points_earn_rate    NUMBER(5,2)     DEFAULT 1.00,
    free_tickets_year   NUMBER(2)       DEFAULT 0,
    companion_tickets   NUMBER(2)       DEFAULT 0,
    concession_vouchers_year NUMBER(2)  DEFAULT 0,
    priority_booking    CHAR(1)         DEFAULT 'N',
    exclusive_events    CHAR(1)         DEFAULT 'N',
    free_upgrades       CHAR(1)         DEFAULT 'N',
    early_access_hours  NUMBER(3)       DEFAULT 0,
    tier_color          VARCHAR2(7),
    tier_icon           VARCHAR2(50),
    display_order       NUMBER(3),
    is_active           CHAR(1)         DEFAULT 'Y',
    created_date        DATE            DEFAULT SYSDATE,
    created_by          VARCHAR2(30)    DEFAULT USER,
    last_modified_date  DATE            DEFAULT SYSDATE,
    last_modified_by    VARCHAR2(30)    DEFAULT USER,
    
    -- Constraints
    CONSTRAINT chk_dim_tier_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_dim_tier_name CHECK (tier_name IN ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND')),
    CONSTRAINT chk_dim_tier_discount CHECK (discount_percentage >= 0),
    CONSTRAINT chk_dim_tier_points CHECK (points_required >= 0),
    CONSTRAINT chk_dim_tier_priority CHECK (priority_booking IN ('Y','N')),
    CONSTRAINT chk_dim_tier_exclusive CHECK (exclusive_events IN ('Y','N')),
    CONSTRAINT chk_dim_tier_upgrades CHECK (free_upgrades IN ('Y','N'))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_tier_id ON dim_membership_tier(tier_id);
CREATE UNIQUE INDEX uk_dim_tier_code ON dim_membership_tier(tier_code);

-- Indexes
CREATE INDEX idx_dim_tier_points ON dim_membership_tier(points_required);

COMMENT ON TABLE dim_membership_tier IS 'Loyalty program tier dimension (Bronze, Silver, Gold, etc.)';


-- ============================================================
-- DIM_AGE_GROUP - Customer age group dimension
-- ============================================================
CREATE TABLE dim_age_group (
    age_group_sk        NUMBER(12)      CONSTRAINT pk_dim_age_group PRIMARY KEY,
    age_group_id        VARCHAR2(20)    NOT NULL,
    age_group_code      VARCHAR2(20)    NOT NULL,
    age_group_name      VARCHAR2(30)    NOT NULL,
    age_group_description VARCHAR2(255),
    age_min             NUMBER(3)       NOT NULL,
    age_max             NUMBER(3)       NOT NULL,
    age_midpoint        NUMBER(3)       GENERATED ALWAYS AS ((age_min + age_max) / 2) VIRTUAL,
    generation          VARCHAR2(30),
    generation_years    VARCHAR2(50),
    age_segment         VARCHAR2(30),
    display_order       NUMBER(3),
    color_code          VARCHAR2(7),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_age_min CHECK (age_min >= 0),
    CONSTRAINT chk_dim_age_max CHECK (age_max <= 150),
    CONSTRAINT chk_dim_age_range CHECK (age_min <= age_max),
    CONSTRAINT chk_dim_age_generation CHECK (generation IN ('GEN_ALPHA', 'GEN_Z', 'MILLENNIAL', 'GEN_X', 'BOOMER', 'SILENT', NULL)),
    CONSTRAINT chk_dim_age_segment CHECK (age_segment IN ('CHILDREN', 'TEENS', 'YOUNG_ADULTS', 'ADULTS', 'MIDDLE_AGE', 'SENIORS', NULL))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_age_group_id ON dim_age_group(age_group_id);
CREATE UNIQUE INDEX uk_dim_age_group_code ON dim_age_group(age_group_code);

-- Indexes
CREATE INDEX idx_dim_age_group_min ON dim_age_group(age_min);
CREATE INDEX idx_dim_age_group_max ON dim_age_group(age_max);

COMMENT ON TABLE dim_age_group IS 'Customer age group reference dimension';


-- ============================================================
-- DIM_GEOGRAPHY - Geographic location hierarchy
-- ============================================================
CREATE TABLE dim_geography (
    geo_sk              NUMBER(12)      CONSTRAINT pk_dim_geo PRIMARY KEY,
    geo_id              VARCHAR2(20)    NOT NULL,
    geo_code            VARCHAR2(20)    NOT NULL,
    country             VARCHAR2(50)    NOT NULL,
    country_code        VARCHAR2(10)    NOT NULL,
    region              VARCHAR2(50)    NOT NULL,
    region_code         VARCHAR2(20)    NOT NULL,
    city                VARCHAR2(50)    NOT NULL,
    city_code           VARCHAR2(20)    NOT NULL,
    postal_code         VARCHAR2(20),
    district            VARCHAR2(50),
    latitude            NUMBER(10,8),
    longitude           NUMBER(11,8),
    country_sk          NUMBER(12),
    region_sk           NUMBER(12),
    city_sk             NUMBER(12),
    full_location       VARCHAR2(200)   GENERATED ALWAYS AS (city || ', ' || region || ', ' || country) VIRTUAL,
    display_order       NUMBER(3),
    timezone            VARCHAR2(50)    DEFAULT 'Africa/Accra',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_geo_lat CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_dim_geo_long CHECK (longitude BETWEEN -180 AND 180)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_geo_id ON dim_geography(geo_id);
CREATE UNIQUE INDEX uk_dim_geo_code ON dim_geography(geo_code);

-- Foreign keys (self-referencing)
ALTER TABLE dim_geography ADD CONSTRAINT fk_dim_geo_country 
    FOREIGN KEY (country_sk) REFERENCES dim_geography(geo_sk);
ALTER TABLE dim_geography ADD CONSTRAINT fk_dim_geo_region 
    FOREIGN KEY (region_sk) REFERENCES dim_geography(geo_sk);
ALTER TABLE dim_geography ADD CONSTRAINT fk_dim_geo_city 
    FOREIGN KEY (city_sk) REFERENCES dim_geography(geo_sk);

-- Indexes
CREATE INDEX idx_dim_geo_country ON dim_geography(country);
CREATE INDEX idx_dim_geo_region ON dim_geography(region);
CREATE INDEX idx_dim_geo_city ON dim_geography(city);

COMMENT ON TABLE dim_geography IS 'Geographic location hierarchy dimension';


-- ============================================================
-- DIM_DEVICE - Customer device dimension
-- ============================================================
CREATE TABLE dim_device (
    device_sk           NUMBER(12)      CONSTRAINT pk_dim_device PRIMARY KEY,
    device_id           VARCHAR2(20)    NOT NULL,
    device_code         VARCHAR2(20)    NOT NULL,
    device_name         VARCHAR2(50)    NOT NULL,
    device_description  VARCHAR2(255),
    device_category     VARCHAR2(30)    NOT NULL,
    device_type         VARCHAR2(30),
    platform            VARCHAR2(30),
    platform_version    VARCHAR2(30),
    browser             VARCHAR2(50),
    browser_version     VARCHAR2(30),
    is_mobile           CHAR(1)         DEFAULT 'N',
    is_tablet           CHAR(1)         DEFAULT 'N',
    is_desktop          CHAR(1)         DEFAULT 'N',
    mobile_os           VARCHAR2(30),
    screen_resolution   VARCHAR2(30),
    screen_size_inches  NUMBER(4,1),
    device_tags         VARCHAR2(255),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_device_mobile CHECK (is_mobile IN ('Y','N')),
    CONSTRAINT chk_dim_device_tablet CHECK (is_tablet IN ('Y','N')),
    CONSTRAINT chk_dim_device_desktop CHECK (is_desktop IN ('Y','N')),
    CONSTRAINT chk_dim_device_category CHECK (device_category IN ('DESKTOP', 'MOBILE', 'TABLET', 'SMART_TV', 'GAMING_CONSOLE', 'OTHER')),
    CONSTRAINT chk_dim_device_platform CHECK (platform IN ('WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID', 'WEBOS', 'TIZEN', 'OTHER', NULL)),
    CONSTRAINT chk_dim_device_browser CHECK (browser IN ('CHROME', 'SAFARI', 'FIREFOX', 'EDGE', 'OPERA', 'BRAVE', 'OTHER', NULL))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_device_id ON dim_device(device_id);
CREATE UNIQUE INDEX uk_dim_device_code ON dim_device(device_code);

-- Indexes
CREATE INDEX idx_dim_device_category ON dim_device(device_category);
CREATE INDEX idx_dim_device_platform ON dim_device(platform);

COMMENT ON TABLE dim_device IS 'Customer device information dimension';


-- ============================================================
-- DIM_MOVIE_STATUS - Movie release status dimension
-- ============================================================
CREATE TABLE dim_movie_status (
    status_sk           NUMBER(12)      CONSTRAINT pk_dim_movie_status PRIMARY KEY,
    status_id           VARCHAR2(20)    NOT NULL,
    status_code         VARCHAR2(20)    NOT NULL,
    status_name         VARCHAR2(30)    NOT NULL,
    status_description  VARCHAR2(255),
    is_released         CHAR(1)         DEFAULT 'N',
    is_upcoming         CHAR(1)         DEFAULT 'N',
    is_post_production  CHAR(1)         DEFAULT 'N',
    is_cancelled        CHAR(1)         DEFAULT 'N',
    is_available        CHAR(1)         DEFAULT 'N',
    status_category     VARCHAR2(30),
    display_order       NUMBER(3),
    color_code          VARCHAR2(7),
    icon_class          VARCHAR2(50),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_mov_status_released CHECK (is_released IN ('Y','N')),
    CONSTRAINT chk_dim_mov_status_upcoming CHECK (is_upcoming IN ('Y','N')),
    CONSTRAINT chk_dim_mov_status_post CHECK (is_post_production IN ('Y','N')),
    CONSTRAINT chk_dim_mov_status_cancelled CHECK (is_cancelled IN ('Y','N')),
    CONSTRAINT chk_dim_mov_status_available CHECK (is_available IN ('Y','N')),
    CONSTRAINT chk_dim_mov_status_cat CHECK (status_category IN ('RELEASED', 'PRE_RELEASE', 'POST_RELEASE', 'CANCELLED', NULL))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_movie_status_id ON dim_movie_status(status_id);
CREATE UNIQUE INDEX uk_dim_movie_status_code ON dim_movie_status(status_code);

-- Indexes
CREATE INDEX idx_dim_movie_status_cat ON dim_movie_status(status_category);

COMMENT ON TABLE dim_movie_status IS 'Movie release status reference dimension';


-- ============================================================
-- DIM_SHOWTIME - Showtime session attributes
-- ============================================================
CREATE TABLE dim_showtime (
    showtime_sk         NUMBER(12)      CONSTRAINT pk_dim_showtime PRIMARY KEY,
    showtime_id         VARCHAR2(20)    NOT NULL,
    showtime_code       VARCHAR2(20)    NOT NULL,
    session_type        VARCHAR2(30)    NOT NULL,
    session_timing      VARCHAR2(20)    NOT NULL,
    day_part            VARCHAR2(20)    NOT NULL,
    time_slot           VARCHAR2(20),
    start_hour          NUMBER(2)       NOT NULL,
    end_hour            NUMBER(2)       NOT NULL,
    hour_range          VARCHAR2(20)    NOT NULL,
    is_peak_time        CHAR(1)         DEFAULT 'N',
    is_holiday          CHAR(1)         DEFAULT 'N',
    is_weekend          CHAR(1)         DEFAULT 'N',
    is_special          CHAR(1)         DEFAULT 'N',
    weekday_weekend     VARCHAR2(10)    NOT NULL,
    price_tier          VARCHAR2(20)    DEFAULT 'STANDARD',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_showtime_peak CHECK (is_peak_time IN ('Y','N')),
    CONSTRAINT chk_dim_showtime_holiday CHECK (is_holiday IN ('Y','N')),
    CONSTRAINT chk_dim_showtime_weekend CHECK (is_weekend IN ('Y','N')),
    CONSTRAINT chk_dim_showtime_special CHECK (is_special IN ('Y','N')),
    CONSTRAINT chk_dim_showtime_type CHECK (session_type IN ('MORNING', 'MATINEE', 'EVENING', 'LATE_NIGHT', 'PREMIERE', 'SPECIAL')),
    CONSTRAINT chk_dim_showtime_timing CHECK (session_timing IN ('EARLY_BIRD', 'STANDARD', 'PRIME', 'LATE_NIGHT')),
    CONSTRAINT chk_dim_showtime_daypart CHECK (day_part IN ('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT')),
    CONSTRAINT chk_dim_showtime_wknd CHECK (weekday_weekend IN ('WEEKDAY', 'WEEKEND')),
    CONSTRAINT chk_dim_showtime_price CHECK (price_tier IN ('STANDARD', 'PREMIUM', 'DISCOUNT')),
    CONSTRAINT chk_dim_showtime_hours CHECK (start_hour BETWEEN 0 AND 23 AND end_hour BETWEEN 0 AND 23)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_showtime_id ON dim_showtime(showtime_id);
CREATE UNIQUE INDEX uk_dim_showtime_code ON dim_showtime(showtime_code);

-- Indexes
CREATE INDEX idx_dim_showtime_type ON dim_showtime(session_type);
CREATE INDEX idx_dim_showtime_timing ON dim_showtime(session_timing);

COMMENT ON TABLE dim_showtime IS 'Showtime session attributes dimension';


-- ============================================================
-- DIM_BRANCH - Cinema branch dimension
-- ============================================================
CREATE TABLE dim_branch (
    branch_sk           NUMBER(12)      CONSTRAINT pk_dim_branch PRIMARY KEY,
    branch_id           VARCHAR2(20)    NOT NULL,
    branch_code         VARCHAR2(20)    NOT NULL,
    branch_name         VARCHAR2(100)   NOT NULL,
    address_line1       VARCHAR2(100),
    address_line2       VARCHAR2(100),
    city                VARCHAR2(50)    NOT NULL,
    region              VARCHAR2(50)    NOT NULL,
    country             VARCHAR2(50)    NOT NULL,
    postal_code         VARCHAR2(20),
    mall_name           VARCHAR2(100),
    geo_sk              NUMBER(12),
    number_of_screens   NUMBER(3)       NOT NULL,
    total_capacity      NUMBER(6)       NOT NULL,
    phone_number        VARCHAR2(20),
    email               VARCHAR2(100),
    manager_name        VARCHAR2(100),
    opening_date        DATE            NOT NULL,
    closing_date        DATE,
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    timezone            VARCHAR2(50)    DEFAULT 'Africa/Accra',
    currency_code       VARCHAR2(3)     DEFAULT 'GHS',
    latitude            NUMBER(10,8),
    longitude           NUMBER(11,8),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_branch_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'UNDER_RENOVATION', 'PERMANENTLY_CLOSED')),
    CONSTRAINT chk_dim_branch_capacity CHECK (total_capacity >= 0),
    CONSTRAINT chk_dim_branch_screens CHECK (number_of_screens >= 0),
    CONSTRAINT chk_dim_branch_lat CHECK (latitude BETWEEN -90 AND 90 OR latitude IS NULL),
    CONSTRAINT chk_dim_branch_long CHECK (longitude BETWEEN -180 AND 180 OR longitude IS NULL)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_branch_id ON dim_branch(branch_id);
CREATE UNIQUE INDEX uk_dim_branch_code ON dim_branch(branch_code);

-- Foreign key
ALTER TABLE dim_branch ADD CONSTRAINT fk_dim_branch_geo 
    FOREIGN KEY (geo_sk) REFERENCES dim_geography(geo_sk);

-- Indexes
CREATE INDEX idx_dim_branch_city ON dim_branch(city);
CREATE INDEX idx_dim_branch_region ON dim_branch(region);
CREATE INDEX idx_dim_branch_status ON dim_branch(status);
CREATE INDEX idx_dim_branch_geo ON dim_branch(geo_sk);

COMMENT ON TABLE dim_branch IS 'Cinema branch location dimension';


-- ============================================================
-- DIM_SUPPLIER - Vendor and supplier dimension
-- ============================================================
CREATE TABLE dim_supplier (
    supplier_sk         NUMBER(12)      CONSTRAINT pk_dim_supplier PRIMARY KEY,
    supplier_id         VARCHAR2(20)    NOT NULL,
    supplier_code       VARCHAR2(20)    NOT NULL,
    supplier_name       VARCHAR2(100)   NOT NULL,
    supplier_alias      VARCHAR2(50),
    supplier_type       VARCHAR2(30)    NOT NULL,
    contact_name        VARCHAR2(100),
    contact_phone       VARCHAR2(20),
    contact_email       VARCHAR2(100),
    website             VARCHAR2(200),
    address_line1       VARCHAR2(100),
    address_line2       VARCHAR2(100),
    city                VARCHAR2(50),
    region              VARCHAR2(50),
    country             VARCHAR2(50),
    postal_code         VARCHAR2(20),
    geo_sk              NUMBER(12),
    payment_terms       VARCHAR2(50)    DEFAULT 'NET 30',
    tax_id              VARCHAR2(50),
    quality_rating      NUMBER(2,1),
    delivery_rating     NUMBER(2,1),
    price_rating        NUMBER(2,1),
    overall_rating      NUMBER(2,1)     GENERATED ALWAYS AS ((quality_rating + delivery_rating + price_rating) / 3) VIRTUAL,
    lead_time_days      NUMBER(3)       DEFAULT 3,
    min_order_value     NUMBER(10,2)    DEFAULT 0,
    preferred_delivery_day VARCHAR2(10),
    is_preferred        CHAR(1)         DEFAULT 'N',
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    contract_start      DATE,
    contract_end        DATE,
    created_date        DATE            DEFAULT SYSDATE,
    created_by          VARCHAR2(30)    DEFAULT USER,
    last_modified_date  DATE            DEFAULT SYSDATE,
    last_modified_by    VARCHAR2(30)    DEFAULT USER,
    
    -- Constraints
    CONSTRAINT chk_dim_supplier_rating_q CHECK (quality_rating BETWEEN 1 AND 5 OR quality_rating IS NULL),
    CONSTRAINT chk_dim_supplier_rating_d CHECK (delivery_rating BETWEEN 1 AND 5 OR delivery_rating IS NULL),
    CONSTRAINT chk_dim_supplier_rating_p CHECK (price_rating BETWEEN 1 AND 5 OR price_rating IS NULL),
    CONSTRAINT chk_dim_supplier_type CHECK (supplier_type IN ('FOOD', 'BEVERAGE', 'EQUIPMENT', 'MERCHANDISE', 'SERVICE', 'MULTI')),
    CONSTRAINT chk_dim_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BLACKLISTED')),
    CONSTRAINT chk_dim_supplier_preferred CHECK (is_preferred IN ('Y','N'))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_supplier_id ON dim_supplier(supplier_id);
CREATE UNIQUE INDEX uk_dim_supplier_code ON dim_supplier(supplier_code);

-- Foreign key
ALTER TABLE dim_supplier ADD CONSTRAINT fk_dim_supplier_geo 
    FOREIGN KEY (geo_sk) REFERENCES dim_geography(geo_sk);

-- Indexes
CREATE INDEX idx_dim_supplier_name ON dim_supplier(supplier_name);
CREATE INDEX idx_dim_supplier_type ON dim_supplier(supplier_type);
CREATE INDEX idx_dim_supplier_status ON dim_supplier(status);
CREATE INDEX idx_dim_supplier_geo ON dim_supplier(geo_sk);

COMMENT ON TABLE dim_supplier IS 'Vendor and supplier dimension';


-- ============================================================
-- DIM_SCREEN - Individual screen/auditorium dimension
-- ============================================================
CREATE TABLE dim_screen (
    screen_sk           NUMBER(12)      CONSTRAINT pk_dim_screen PRIMARY KEY,
    screen_id           VARCHAR2(20)    NOT NULL,
    screen_code         VARCHAR2(20)    NOT NULL,
    screen_number       VARCHAR2(10)    NOT NULL,
    screen_name         VARCHAR2(50),
    branch_sk           NUMBER(12)      NOT NULL,
    screen_type         VARCHAR2(30)    NOT NULL,
    projection_type     VARCHAR2(20),
    sound_system        VARCHAR2(30),
    is_3d               CHAR(1)         DEFAULT 'N',
    is_imax             CHAR(1)         DEFAULT 'N',
    is_dolby_atmos      CHAR(1)         DEFAULT 'N',
    is_vip              CHAR(1)         DEFAULT 'N',
    is_accessibility    CHAR(1)         DEFAULT 'N',
    capacity            NUMBER(6)       NOT NULL,
    row_count           NUMBER(3),
    seats_per_row       NUMBER(3),
    screen_width_cm     NUMBER(6),
    screen_height_cm    NUMBER(6),
    room_width_cm       NUMBER(6),
    room_height_cm      NUMBER(6),
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_screen_3d CHECK (is_3d IN ('Y','N')),
    CONSTRAINT chk_dim_screen_imax CHECK (is_imax IN ('Y','N')),
    CONSTRAINT chk_dim_screen_atmos CHECK (is_dolby_atmos IN ('Y','N')),
    CONSTRAINT chk_dim_screen_vip CHECK (is_vip IN ('Y','N')),
    CONSTRAINT chk_dim_screen_access CHECK (is_accessibility IN ('Y','N')),
    CONSTRAINT chk_dim_screen_type CHECK (screen_type IN ('STANDARD', 'IMAX', 'DOLBY', '4DX', 'VIP', 'D-BOX', 'SCREENX', 'PREMIUM')),
    CONSTRAINT chk_dim_screen_proj CHECK (projection_type IN ('DIGITAL', 'LASER', 'FILM', 'DLP', '4K', NULL)),
    CONSTRAINT chk_dim_screen_sound CHECK (sound_system IN ('DOLBY_7_1', 'DOLBY_ATMOS', 'DTS_X', 'AURA', 'STANDARD', NULL)),
    CONSTRAINT chk_dim_screen_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'UNDER_MAINTENANCE', 'RETIRED')),
    CONSTRAINT chk_dim_screen_capacity CHECK (capacity >= 0)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_screen_id ON dim_screen(screen_id);
CREATE UNIQUE INDEX uk_dim_screen_code ON dim_screen(screen_code);

-- Foreign key
ALTER TABLE dim_screen ADD CONSTRAINT fk_dim_screen_branch 
    FOREIGN KEY (branch_sk) REFERENCES dim_branch(branch_sk);

-- Indexes
CREATE INDEX idx_dim_screen_branch ON dim_screen(branch_sk);
CREATE INDEX idx_dim_screen_type ON dim_screen(screen_type);
CREATE INDEX idx_dim_screen_status ON dim_screen(status);

COMMENT ON TABLE dim_screen IS 'Individual cinema screen/auditorium dimension';


-- ============================================================
-- DIM_SEAT - Individual seat dimension
-- ============================================================
CREATE TABLE dim_seat (
    seat_sk             NUMBER(12)      CONSTRAINT pk_dim_seat PRIMARY KEY,
    seat_id             VARCHAR2(20)    NOT NULL,
    seat_code           VARCHAR2(20)    NOT NULL,
    screen_sk           NUMBER(12)      NOT NULL,
    branch_sk           NUMBER(12)      NOT NULL,
    seat_number         VARCHAR2(10)    NOT NULL,
    row_letter          VARCHAR2(2)     NOT NULL,
    seat_position       NUMBER(3)       NOT NULL,
    seat_type           VARCHAR2(20)    NOT NULL,
    price_tier          VARCHAR2(10)    NOT NULL,
    is_wheelchair_accessible CHAR(1)   DEFAULT 'N',
    is_accessible_aisle CHAR(1)         DEFAULT 'N',
    is_hearing_impaired CHAR(1)         DEFAULT 'N',
    is_vision_impaired  CHAR(1)         DEFAULT 'N',
    has_cup_holder      CHAR(1)         DEFAULT 'Y',
    has_table           CHAR(1)         DEFAULT 'N',
    has_power_outlet    CHAR(1)         DEFAULT 'N',
    has_call_button     CHAR(1)         DEFAULT 'N',
    viewing_angle       NUMBER(5,2),
    distance_from_screen NUMBER(5,2),
    view_quality        VARCHAR2(20),
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_seat_wheelchair CHECK (is_wheelchair_accessible IN ('Y','N')),
    CONSTRAINT chk_dim_seat_aisle CHECK (is_accessible_aisle IN ('Y','N')),
    CONSTRAINT chk_dim_seat_hearing CHECK (is_hearing_impaired IN ('Y','N')),
    CONSTRAINT chk_dim_seat_vision CHECK (is_vision_impaired IN ('Y','N')),
    CONSTRAINT chk_dim_seat_cup CHECK (has_cup_holder IN ('Y','N')),
    CONSTRAINT chk_dim_seat_table CHECK (has_table IN ('Y','N')),
    CONSTRAINT chk_dim_seat_power CHECK (has_power_outlet IN ('Y','N')),
    CONSTRAINT chk_dim_seat_call CHECK (has_call_button IN ('Y','N')),
    CONSTRAINT chk_dim_seat_type CHECK (seat_type IN ('STANDARD', 'PREMIUM', 'RECLINER', 'VIP', 'ACCESSIBLE', 'LOVESEAT')),
    CONSTRAINT chk_dim_seat_tier CHECK (price_tier IN ('STANDARD', 'PREMIUM', 'VIP', 'COMPANION')),
    CONSTRAINT chk_dim_seat_status CHECK (status IN ('ACTIVE', 'UNDER_MAINTENANCE', 'DAMAGED', 'RETIRED')),
    CONSTRAINT chk_dim_seat_view CHECK (view_quality IN ('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', NULL))
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_seat_id ON dim_seat(seat_id);
CREATE UNIQUE INDEX uk_dim_seat_code ON dim_seat(seat_code);

-- Foreign keys
ALTER TABLE dim_seat ADD CONSTRAINT fk_dim_seat_screen 
    FOREIGN KEY (screen_sk) REFERENCES dim_screen(screen_sk);
ALTER TABLE dim_seat ADD CONSTRAINT fk_dim_seat_branch 
    FOREIGN KEY (branch_sk) REFERENCES dim_branch(branch_sk);

-- Indexes
CREATE INDEX idx_dim_seat_screen ON dim_seat(screen_sk);
CREATE INDEX idx_dim_seat_branch ON dim_seat(branch_sk);
CREATE INDEX idx_dim_seat_type ON dim_seat(seat_type);
CREATE INDEX idx_dim_seat_status ON dim_seat(status);

COMMENT ON TABLE dim_seat IS 'Individual seat dimension for occupancy and seat-level analysis';


-- ============================================================
-- DIM_EMPLOYEE - Staff/Employee dimension
-- ============================================================
CREATE TABLE dim_employee (
    employee_sk         NUMBER(12)      CONSTRAINT pk_dim_employee PRIMARY KEY,
    employee_id         VARCHAR2(20)    NOT NULL,
    employee_code       VARCHAR2(20)    NOT NULL,
    first_name          VARCHAR2(50)    NOT NULL,
    last_name           VARCHAR2(50)    NOT NULL,
    full_name           VARCHAR2(250)   GENERATED ALWAYS AS (first_name || ' ' || last_name) VIRTUAL,
    gender              VARCHAR2(1),
    date_of_birth       DATE,
    age                 NUMBER(3),                          -- Regular column (calculated in ETL)
    email               VARCHAR2(100)   NOT NULL,
    phone               VARCHAR2(20)    NOT NULL,
    branch_sk           NUMBER(12)      NOT NULL,
    position_name       VARCHAR2(50)    NOT NULL,
    role_type           VARCHAR2(30)    NOT NULL,
    position_level      NUMBER(2)       NOT NULL,
    supervisor_sk       NUMBER(12),
    hire_date           DATE            NOT NULL,
    termination_date    DATE,
    employment_type     VARCHAR2(30)    NOT NULL,
    contract_type       VARCHAR2(20),
    shift_preference    VARCHAR2(20),
    department          VARCHAR2(50),
    salary_grade        VARCHAR2(20),
    hourly_rate         NUMBER(10,2),
    commission_rate     NUMBER(5,2)     DEFAULT 0,
    performance_rating  NUMBER(2,1),
    last_review_date    DATE,
    certifications      CLOB,
    skills              CLOB,
    languages_spoken    VARCHAR2(200),
    is_active           CHAR(1)         DEFAULT 'Y',
    employee_status     VARCHAR2(20)    DEFAULT 'ACTIVE',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_employee_gender CHECK (gender IN ('M', 'F', 'O')),
    CONSTRAINT chk_dim_employee_role CHECK (role_type IN ('MANAGEMENT', 'CASHIER', 'PROJECTIONIST', 'USHER', 'CONCESSION_STAFF', 'CLEANER', 'SECURITY', 'MAINTENANCE', 'IT', 'MARKETING', 'HR', 'ACCOUNTING', 'OTHER')),
    CONSTRAINT chk_dim_employee_type CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'TEMPORARY', 'CONTRACT', 'INTERN')),
    CONSTRAINT chk_dim_employee_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_dim_employee_status CHECK (employee_status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED', 'RESIGNED', 'RETIRED')),
    CONSTRAINT chk_dim_employee_rating CHECK (performance_rating BETWEEN 1 AND 5 OR performance_rating IS NULL),
    CONSTRAINT chk_dim_employee_shift CHECK (shift_preference IN ('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'FLEXIBLE')),
    CONSTRAINT chk_dim_employee_position CHECK (position_level BETWEEN 1 AND 6)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_employee_id ON dim_employee(employee_id);
CREATE UNIQUE INDEX uk_dim_employee_code ON dim_employee(employee_code);
CREATE UNIQUE INDEX uk_dim_employee_email ON dim_employee(email);

-- Foreign keys
ALTER TABLE dim_employee ADD CONSTRAINT fk_dim_employee_branch 
    FOREIGN KEY (branch_sk) REFERENCES dim_branch(branch_sk);
ALTER TABLE dim_employee ADD CONSTRAINT fk_dim_employee_supervisor 
    FOREIGN KEY (supervisor_sk) REFERENCES dim_employee(employee_sk);

-- Indexes
CREATE INDEX idx_dim_employee_branch ON dim_employee(branch_sk);
CREATE INDEX idx_dim_employee_role ON dim_employee(role_type);
CREATE INDEX idx_dim_employee_status ON dim_employee(employee_status);
CREATE INDEX idx_dim_employee_supervisor ON dim_employee(supervisor_sk);

COMMENT ON TABLE dim_employee IS 'Staff and employee dimension';


-- ============================================================
-- DIM_PRODUCT - Concession product dimension
-- ============================================================
CREATE TABLE dim_product (
    product_sk          NUMBER(12)      CONSTRAINT pk_dim_product PRIMARY KEY,
    product_id          VARCHAR2(20)    NOT NULL,
    product_code        VARCHAR2(20)    NOT NULL,
    product_name        VARCHAR2(100)   NOT NULL,
    product_description VARCHAR2(500),
    sku                 VARCHAR2(30),
    product_category    VARCHAR2(30)    NOT NULL,
    product_subcategory VARCHAR2(30),
    category_type       VARCHAR2(30)    NOT NULL,
    supplier_sk         NUMBER(12),
    brand               VARCHAR2(50),
    manufacturer        VARCHAR2(50),
    unit_cost           NUMBER(10,2)    NOT NULL,
    selling_price       NUMBER(10,2)    NOT NULL,
    profit_margin       NUMBER(5,2)     GENERATED ALWAYS AS ((selling_price - unit_cost) / selling_price * 100) VIRTUAL,
    tax_rate            NUMBER(5,2)     DEFAULT 0,
    unit_of_measure     VARCHAR2(20)    NOT NULL,
    package_quantity    NUMBER(6)       DEFAULT 1,
    reorder_level       NUMBER(6),
    reorder_quantity    NUMBER(6),
    par_level           NUMBER(6),
    safety_stock        NUMBER(6)       DEFAULT 0,
    is_perishable       CHAR(1)         DEFAULT 'N',
    shelf_life_days     NUMBER(5),
    requires_refrigeration CHAR(1)      DEFAULT 'N',
    contains_allergens  CLOB,
    nutritional_info    CLOB,
    is_active           CHAR(1)         DEFAULT 'Y',
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    image_url           VARCHAR2(500),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_product_perishable CHECK (is_perishable IN ('Y','N')),
    CONSTRAINT chk_dim_product_refrig CHECK (requires_refrigeration IN ('Y','N')),
    CONSTRAINT chk_dim_product_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_dim_product_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED', 'OUT_OF_STOCK')),
    CONSTRAINT chk_dim_product_uom CHECK (unit_of_measure IN ('EACH', 'KG', 'LITRE', 'GRAM', 'ML', 'OUNCE', 'POUND', 'CASE', 'BOX', 'BAG', 'CUP', 'BOTTLE', 'CAN', 'OTHER')),
    CONSTRAINT chk_dim_product_category CHECK (category_type IN ('FOOD', 'BEVERAGE', 'SNACK', 'MERCHANDISE', 'COMBO')),
    CONSTRAINT chk_dim_product_cost CHECK (unit_cost >= 0),
    CONSTRAINT chk_dim_product_price CHECK (selling_price >= 0)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_product_id ON dim_product(product_id);
CREATE UNIQUE INDEX uk_dim_product_code ON dim_product(product_code);

-- Foreign key
ALTER TABLE dim_product ADD CONSTRAINT fk_dim_product_supplier 
    FOREIGN KEY (supplier_sk) REFERENCES dim_supplier(supplier_sk);

-- Indexes
CREATE INDEX idx_dim_product_category ON dim_product(product_category);
CREATE INDEX idx_dim_product_supplier ON dim_product(supplier_sk);
CREATE INDEX idx_dim_product_status ON dim_product(status);

COMMENT ON TABLE dim_product IS 'Concession product dimension';


-- ============================================================
-- DIM_PROMOTION - Promotion and campaign dimension
-- ============================================================
CREATE TABLE dim_promotion (
    promotion_sk        NUMBER(12)      CONSTRAINT pk_dim_promotion PRIMARY KEY,
    promotion_id        VARCHAR2(20)    NOT NULL,
    promotion_code      VARCHAR2(30)    NOT NULL,
    promotion_name      VARCHAR2(100)   NOT NULL,
    promotion_description VARCHAR2(500),
    promotion_type      VARCHAR2(30)    NOT NULL,
    promotion_category  VARCHAR2(30)    NOT NULL,
    discount_value      NUMBER(10,2)    NOT NULL,
    discount_type       VARCHAR2(20)    NOT NULL,
    max_discount_amount NUMBER(10,2),
    min_purchase_amount NUMBER(10,2)    DEFAULT 0,
    start_date          DATE            NOT NULL,
    end_date            DATE            NOT NULL,
    start_time          VARCHAR2(8),
    end_time            VARCHAR2(8),
    days_of_week        VARCHAR2(14),
    target_tiers        CLOB,
    target_genres       CLOB,
    target_branches     CLOB,
    min_ticket_quantity NUMBER(3)       DEFAULT 1,
    max_ticket_quantity NUMBER(3)       DEFAULT 10,
    requires_coupon     CHAR(1)         DEFAULT 'N',
    is_stackable        CHAR(1)         DEFAULT 'N',
    stack_priority      NUMBER(2)       DEFAULT 1,
    usage_limit_per_customer NUMBER(6)  DEFAULT 1,
    usage_limit_total    NUMBER(10)     DEFAULT 0,
    usage_count_current  NUMBER(10)     DEFAULT 0,
    budget_amount        NUMBER(12,2),
    budget_used          NUMBER(12,2)   DEFAULT 0,
    status              VARCHAR2(20)    DEFAULT 'ACTIVE',
    promo_image_url     VARCHAR2(500),
    promo_banner_url    VARCHAR2(500),
    promo_text          CLOB,
    utm_source          VARCHAR2(50),
    utm_medium          VARCHAR2(50),
    utm_campaign        VARCHAR2(50),
    utm_content         VARCHAR2(50),
    created_date        DATE            DEFAULT SYSDATE,
    created_by          VARCHAR2(30)    DEFAULT USER,
    approved_by         VARCHAR2(30),
    approved_date       DATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    last_modified_by    VARCHAR2(30)    DEFAULT USER,
    
    -- Constraints
    CONSTRAINT chk_dim_promo_coupon CHECK (requires_coupon IN ('Y','N')),
    CONSTRAINT chk_dim_promo_stackable CHECK (is_stackable IN ('Y','N')),
    CONSTRAINT chk_dim_promo_type CHECK (promotion_type IN ('PERCENTAGE_DISCOUNT', 'FIXED_DISCOUNT', 'BUY_ONE_GET_ONE', 'FREE_ITEM', 'FREE_TICKET', 'LOYALTY_BONUS', 'REFERRAL', 'FLASH_SALE', 'HOLIDAY_SPECIAL', 'PREMIERE_OFFER', 'MEMBERSHIP_DISCOUNT', 'OTHER')),
    CONSTRAINT chk_dim_promo_category CHECK (promotion_category IN ('TICKET', 'CONCESSION', 'COMBINED', 'MEMBERSHIP', 'GENERAL', 'MERCHANDISE')),
    CONSTRAINT chk_dim_promo_discount_type CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT chk_dim_promo_status CHECK (status IN ('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'EXPIRED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT chk_dim_promo_dates CHECK (start_date <= end_date),
    CONSTRAINT chk_dim_promo_budget CHECK (budget_amount >= 0 OR budget_amount IS NULL)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_promo_id ON dim_promotion(promotion_id);
CREATE UNIQUE INDEX uk_dim_promo_code ON dim_promotion(promotion_code);

-- Indexes
CREATE INDEX idx_dim_promo_type ON dim_promotion(promotion_type);
CREATE INDEX idx_dim_promo_status ON dim_promotion(status);
CREATE INDEX idx_dim_promo_dates ON dim_promotion(start_date, end_date);

COMMENT ON TABLE dim_promotion IS 'Promotion and campaign dimension';


-- ============================================================
-- DIM_MOVIE - Movie metadata dimension (FIXED)
-- ============================================================
CREATE TABLE dim_movie (
    movie_sk            NUMBER(12)      CONSTRAINT pk_dim_movie PRIMARY KEY,
    movie_id            VARCHAR2(20)    NOT NULL,
    tmdb_id             VARCHAR2(20),
    imdb_id             VARCHAR2(20),
    vidapi_id           VARCHAR2(20),
    omdb_id             VARCHAR2(20),
    title               VARCHAR2(200)   NOT NULL,
    original_title      VARCHAR2(200),
    title_sortable      VARCHAR2(4000),
    release_date        DATE,
    release_year        NUMBER(4),
    release_status      VARCHAR2(20),
    runtime_minutes     NUMBER(4),
    language            VARCHAR2(20),
    original_language   VARCHAR2(10),
    synopsis            CLOB,
    tagline             VARCHAR2(500),
    overview            CLOB,
    poster_url          VARCHAR2(500),
    backdrop_url        VARCHAR2(500),
    vote_average        NUMBER(3,1),
    vote_count          NUMBER(8),
    popularity          NUMBER(10,2),
    is_adult            CHAR(1)         DEFAULT 'N',
    is_animated         CHAR(1)         DEFAULT 'N',
    is_foreign          CHAR(1)         DEFAULT 'N',
    is_documentary      CHAR(1)         DEFAULT 'N',
    genre_sk            NUMBER(12),
    certification_sk    NUMBER(12),
    movie_status_sk     NUMBER(12),
    studio              VARCHAR2(100),
    distributor         VARCHAR2(100),
    director            VARCHAR2(100),
    cast                VARCHAR2(500),
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    
    -- Constraints
    CONSTRAINT chk_dim_movie_adult CHECK (is_adult IN ('Y','N')),
    CONSTRAINT chk_dim_movie_animated CHECK (is_animated IN ('Y','N')),
    CONSTRAINT chk_dim_movie_foreign CHECK (is_foreign IN ('Y','N')),
    CONSTRAINT chk_dim_movie_doc CHECK (is_documentary IN ('Y','N')),
    CONSTRAINT chk_dim_movie_release CHECK (release_status IN ('RELEASED', 'UNRELEASED', 'POST_PRODUCTION', 'CANCELLED')),
    CONSTRAINT chk_dim_movie_year CHECK (release_year >= 1900 OR release_year IS NULL),
    CONSTRAINT chk_dim_movie_runtime CHECK (runtime_minutes > 0 OR runtime_minutes IS NULL),
    CONSTRAINT chk_dim_movie_rating CHECK (vote_average BETWEEN 0 AND 10 OR vote_average IS NULL)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_movie_id ON dim_movie(movie_id);

-- Foreign keys
ALTER TABLE dim_movie ADD CONSTRAINT fk_dim_movie_genre 
    FOREIGN KEY (genre_sk) REFERENCES dim_genre(genre_sk);
ALTER TABLE dim_movie ADD CONSTRAINT fk_dim_movie_cert 
    FOREIGN KEY (certification_sk) REFERENCES dim_certification(cert_sk);
ALTER TABLE dim_movie ADD CONSTRAINT fk_dim_movie_status 
    FOREIGN KEY (movie_status_sk) REFERENCES dim_movie_status(status_sk);

-- Indexes
CREATE INDEX idx_dim_movie_title ON dim_movie(title);
CREATE INDEX idx_dim_movie_release ON dim_movie(release_year);
CREATE INDEX idx_dim_movie_genre ON dim_movie(genre_sk);
CREATE INDEX idx_dim_movie_cert ON dim_movie(certification_sk);
CREATE INDEX idx_dim_movie_status ON dim_movie(movie_status_sk);
CREATE INDEX idx_dim_movie_rating ON dim_movie(vote_average);
CREATE INDEX idx_dim_movie_popularity ON dim_movie(popularity DESC);

COMMENT ON TABLE dim_movie IS 'Movie metadata dimension with references to genre, certification, and status';


-- ============================================================
-- DIM_CUSTOMER - Customer dimension with SCD Type 2
-- ============================================================
CREATE TABLE dim_customer (
    customer_sk         NUMBER(12)      CONSTRAINT pk_dim_customer PRIMARY KEY,
    customer_id         VARCHAR2(20)    NOT NULL,
    customer_guid       VARCHAR2(36)    UNIQUE,
    first_name          VARCHAR2(50),
    last_name           VARCHAR2(50),
    full_name           VARCHAR2(250)   GENERATED ALWAYS AS (first_name || ' ' || last_name) VIRTUAL,
    gender              VARCHAR2(1),
    date_of_birth       DATE,
    age                 NUMBER(3),                          -- Regular column (calculated in ETL)
    age_group_sk        NUMBER(12),
    email               VARCHAR2(100),
    phone               VARCHAR2(20),
    city                VARCHAR2(50),
    region              VARCHAR2(50),
    country             VARCHAR2(50)    DEFAULT 'Ghana',
    geo_sk              NUMBER(12),
    occupation          VARCHAR2(50),
    membership_tier_sk  NUMBER(12),
    membership_tier     VARCHAR2(20),
    join_date           DATE,
    favorite_genre_sk   NUMBER(12),
    favorite_genre      VARCHAR2(30),
    preferred_channel_sk NUMBER(12),
    preferred_branch_sk NUMBER(12),
    avg_weekly_spend    NUMBER(10,2),
    customer_lifetime_value NUMBER(12,2),
    churn_risk_score    NUMBER(3,2),
    recency_days        NUMBER(5),
    frequency_per_month NUMBER(3,1),
    monetary_percentile NUMBER(3,0),
    total_visits        NUMBER(6)       DEFAULT 0,
    total_spent         NUMBER(12,2)    DEFAULT 0,
    marketing_consent   CHAR(1)         DEFAULT 'Y',
    data_privacy_consent CHAR(1)        DEFAULT 'Y',
    effective_start_date DATE           NOT NULL,
    effective_end_date   DATE,
    is_current          CHAR(1)         DEFAULT 'Y',
    created_date        DATE            DEFAULT SYSDATE,
    last_modified_date  DATE            DEFAULT SYSDATE,
    modified_by         VARCHAR2(30)    DEFAULT USER,
    
    -- Constraints
    CONSTRAINT chk_dim_customer_gender CHECK (gender IN ('M', 'F', 'O', 'U')),
    CONSTRAINT chk_dim_customer_marketing CHECK (marketing_consent IN ('Y','N')),
    CONSTRAINT chk_dim_customer_privacy CHECK (data_privacy_consent IN ('Y','N')),
    CONSTRAINT chk_dim_customer_current CHECK (is_current IN ('Y','N')),
    CONSTRAINT chk_dim_customer_tier CHECK (membership_tier IN ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND')),
    CONSTRAINT chk_dim_customer_churn CHECK (churn_risk_score BETWEEN 0 AND 1)
);

-- Unique constraints
CREATE UNIQUE INDEX uk_dim_customer_id ON dim_customer(customer_id);

-- Foreign keys
ALTER TABLE dim_customer ADD CONSTRAINT fk_dim_customer_age 
    FOREIGN KEY (age_group_sk) REFERENCES dim_age_group(age_group_sk);
ALTER TABLE dim_customer ADD CONSTRAINT fk_dim_customer_geo 
    FOREIGN KEY (geo_sk) REFERENCES dim_geography(geo_sk);
ALTER TABLE dim_customer ADD CONSTRAINT fk_dim_customer_tier 
    FOREIGN KEY (membership_tier_sk) REFERENCES dim_membership_tier(tier_sk);
ALTER TABLE dim_customer ADD CONSTRAINT fk_dim_customer_genre 
    FOREIGN KEY (favorite_genre_sk) REFERENCES dim_genre(genre_sk);
ALTER TABLE dim_customer ADD CONSTRAINT fk_dim_customer_channel 
    FOREIGN KEY (preferred_channel_sk) REFERENCES dim_channel(channel_sk);
ALTER TABLE dim_customer ADD CONSTRAINT fk_dim_customer_branch 
    FOREIGN KEY (preferred_branch_sk) REFERENCES dim_branch(branch_sk);

-- Indexes
CREATE INDEX idx_dim_customer_current ON dim_customer(is_current);
CREATE INDEX idx_dim_customer_tier ON dim_customer(membership_tier_sk);
CREATE INDEX idx_dim_customer_age ON dim_customer(age_group_sk);
CREATE INDEX idx_dim_customer_geo ON dim_customer(geo_sk);
CREATE INDEX idx_dim_customer_churn ON dim_customer(churn_risk_score);
CREATE INDEX idx_dim_customer_clv ON dim_customer(customer_lifetime_value DESC);

COMMENT ON TABLE dim_customer IS 'Customer dimension with SCD Type 2 for historical tracking';